### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by mrJungle** [gym-service/gym-server#1]
Non esiste la versione django-tenant-schemas==34c474

Non ho capito se da ciò dipende qualcosaltro, ma in locale non riesco più a far partire il server:
(env)davide@davidepc:~/dati/06_Prog/201510_gymservice/gym-server/gym_server$ python manage.py runserver hexxie.com:8000
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/davide/dati/06_Prog/201510_gymservice/env/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/davide/dati/06_Prog/201510_gymservice/env/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/davide/dati/06_Prog/201510_gymservice/env/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 176, in fetch_command
    commands = get_commands()
  File "/home/davide/dati/06_Prog/201510_gymservice/env/local/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(_args, *_kwds)
  File "/home/davide/dati/06_Prog/201510_gymservice/env/local/lib/python2.7/site-packages/django/core/management/**init**.py", line 71, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "/home/davide/dati/06_Prog/201510_gymservice/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "/home/davide/dati/06_Prog/201510_gymservice/env/local/lib/python2.7/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by mrJungle** [comment]
Dopo aver rimosso la verisione e updatato il requirements mi funziona.

Congelo  i requirements e li pusho.
